server:
  port: 8080
spring:
  datasource:
    password: root
    url: jdbc:mysql://mysql-server:3306/devsu
    username: root
    driver-className: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
custom:
  mongo:
    host: mongodb-server
    port: 27017
    database: admin
    user: myUser
    password: userPassForTest1234
    time-out: 5000